# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-2019'
  # name: 'Zup-SA-Win-Op-SVDWEB05'
  # name: 'SA-Win-Op-SVDWEB01'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- powershell: choco upgrade googlechrome
  displayName: 'Instalando Chrome'

- script: |
    npm install && node node_modules/protractor/bin/webdriver-manager update
  displayName: 'npm install and update webdriver'

- script: |
    npm run cadastro-jsm
  displayName: 'Execute cadastro feature'